# Recurrent Neural Network

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Data Preprocessing

In [2]:
dataset_train =  pd.read_csv("dataset_dl/ETH-USD-Train.csv")
display(dataset_train)

Date         Open         High          Low        Close  \
0    25-11-2021  4271.394531  4550.518066  4249.774414  4274.743164   
1    26-11-2021  4522.208984  4550.842285  3933.506592  4030.908936   
2    27-11-2021  4042.999023  4187.684082  4033.513916  4096.912109   
3    28-11-2021  4101.648926  4297.916504  3989.969971  4294.453613   
4    29-11-2021  4296.946777  4460.848633  4284.504883  4445.104980   
..          ...          ...          ...          ...          ...   
361         NaN          NaN          NaN          NaN          NaN   
362         NaN          NaN          NaN          NaN          NaN   
363         NaN          NaN          NaN          NaN          NaN   
364         NaN          NaN          NaN          NaN          NaN   
365         NaN          NaN          NaN          NaN          NaN   

       Adj Close        Volume  
0    4274.743164  1.870536e+10  
1    4030.908936  2.628180e+10  
2    4096.912109  1.651569e+10  
3    4294.453613  1.595313e+10  
4    4445.104980  1.908648e+10  
..           ...           ...  
361          NaN           NaN  
362          NaN           NaN  
363          NaN           NaN  
364          NaN           NaN  
365          NaN           NaN  

[366 rows x 7 columns]

In [3]:
# Dropping NaN rows
dataset_train = dataset_train.dropna()

In [4]:
# Opening price of ETH (in USD)
training_set = dataset_train.iloc[:,1:2].values

In [5]:
print(training_set)

[[4271.394531]
 [4522.208984]
 [4042.999023]
 [4101.648926]
 [4296.946777]
 [4447.768066]
 [4623.679688]
 [4586.333008]
 [4514.355957]
 [4227.762207]
 [4119.628906]
 [4199.      ]
 [4358.586914]
 [4311.674316]
 [4433.024902]
 [4113.588379]
 [3909.667725]
 [4084.811279]
 [4136.359863]
 [3782.822754]
 [3862.251465]
 [4020.415039]
 [3959.012451]
 [3880.291504]
 [3960.872314]
 [3923.695801]
 [3938.463867]
 [4018.695801]
 [3981.96167 ]
 [4111.345215]
 [4049.781982]
 [4094.151611]
 [4064.746338]
 [4037.538086]
 [3797.436279]
 [3632.219727]
 [3713.430176]
 [3683.047119]
 [3769.29834 ]
 [3829.535645]
 [3761.361572]
 [3794.269043]
 [3549.708984]
 [3417.837891]
 [3193.502441]
 [3091.696289]
 [3157.570557]
 [3082.990967]
 [3238.449951]
 [3372.10498 ]
 [3248.648682]
 [3309.844238]
 [3330.387207]
 [3350.947266]
 [3212.287598]
 [3163.850342]
 [3095.271729]
 [3002.956787]
 [2561.145264]
 [2406.924316]
 [2535.891113]
 [2440.393555]
 [2455.579102]
 [2467.188477]
 [2421.646973]
 [2546.590576]
 [2598.564

In [6]:
# Feature Scalling by doing Normalization
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
training_set_scaled = sc.fit_transform(training_set)

In [7]:
print(training_set_scaled)
print(f"\nNo of Elemets: {len(training_set_scaled)}")

[[0.90295921]
 [0.97204879]
 [0.84004517]
 [0.85620093]
 [0.90999785]
 [0.95154322]
 [1.        ]
 [0.98971245]
 [0.96988558]
 [0.89094021]
 [0.86115371]
 [0.88301734]
 [0.9269773 ]
 [0.91405471]
 [0.94748206]
 [0.85948978]
 [0.80331761]
 [0.85156281]
 [0.86576243]
 [0.76837678]
 [0.79025628]
 [0.83382417]
 [0.81691015]
 [0.79522561]
 [0.81742247]
 [0.8071818 ]
 [0.81124982]
 [0.83335058]
 [0.82323177]
 [0.85887188]
 [0.84191361]
 [0.85413571]
 [0.84603571]
 [0.8385409 ]
 [0.77240223]
 [0.72689153]
 [0.74926183]
 [0.74089249]
 [0.76465133]
 [0.78124435]
 [0.76246506]
 [0.77152978]
 [0.70416304]
 [0.66783771]
 [0.60604206]
 [0.57799845]
 [0.59614423]
 [0.57560047]
 [0.61842335]
 [0.65524008]
 [0.6212327 ]
 [0.63808968]
 [0.64374847]
 [0.64941196]
 [0.61121664]
 [0.59787407]
 [0.57898334]
 [0.55355418]
 [0.43185237]
 [0.38937053]
 [0.42489584]
 [0.39859   ]
 [0.40277302]
 [0.40597095]
 [0.39342605]
 [0.42784313]
 [0.44216003]
 [0.44345428]
 [0.46676805]
 [0.49543253]
 [0.46520541]
 [0.46

In [8]:
print("Statistical Summary of Feature Scaled Data:")
pd.DataFrame(training_set_scaled).describe()

Statistical Summary of Feature Scaled Data:


0
count  273.000000
mean     0.437313
std      0.258616
min      0.000000
25%      0.219347
50%      0.464884
75%      0.600173
max      1.000000

In [9]:
# Creating a Data Structure with 60 timestamps (2 months) and 1 output

X_train = []
y_train = []
for i in range(60, len(training_set_scaled)):
    X_train.append(training_set_scaled[i-60:i,0])
    y_train.append(training_set_scaled[i,0])
    
X_train, y_train = np.array(X_train), np.array(y_train)

In [10]:
X_train[0]

array([0.90295921, 0.97204879, 0.84004517, 0.85620093, 0.90999785,
       0.95154322, 1.        , 0.98971245, 0.96988558, 0.89094021,
       0.86115371, 0.88301734, 0.9269773 , 0.91405471, 0.94748206,
       0.85948978, 0.80331761, 0.85156281, 0.86576243, 0.76837678,
       0.79025628, 0.83382417, 0.81691015, 0.79522561, 0.81742247,
       0.8071818 , 0.81124982, 0.83335058, 0.82323177, 0.85887188,
       0.84191361, 0.85413571, 0.84603571, 0.8385409 , 0.77240223,
       0.72689153, 0.74926183, 0.74089249, 0.76465133, 0.78124435,
       0.76246506, 0.77152978, 0.70416304, 0.66783771, 0.60604206,
       0.57799845, 0.59614423, 0.57560047, 0.61842335, 0.65524008,
       0.6212327 , 0.63808968, 0.64374847, 0.64941196, 0.61121664,
       0.59787407, 0.57898334, 0.55355418, 0.43185237, 0.38937053])

In [11]:
data_size, timestep = X_train.shape
print(data_size,",", timestep)


213 , 60


In [12]:
# Reshaping Data as (Observations, Timestamp, Indicators)
X_train = np.reshape(X_train, newshape=(data_size, timestep, 1))


In [13]:
X_train.shape

(213, 60, 1)

## Building RNN

### Importing Keras libraries

In [21]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout

### Initialize RNN

In [22]:
model = Sequential()

### Adding LSTM layer with dropout regularization

In [23]:
# LSTM Layer 1
model.add(LSTM(units=100, return_sequences=True, input_shape=(timestep, 1)))
model.add(Dropout(0.2))
# LSTM Layer 2
model.add(LSTM(units=100, return_sequences=True))
model.add(Dropout(0.2))
# LSTM Layer 3
model.add(LSTM(units=100, return_sequences=True))
model.add(Dropout(0.2))
# LSTM Layer 4
model.add(LSTM(units=100))
model.add(Dropout(0.2))

# Output Layer
model.add(Dense(units=1))

### Compiling Model

In [24]:
# Recommended Optimizer for RNN is 'rmsprop'
model.compile(optimizer= 'adam', loss='mse')

In [25]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 60, 100)           40800     
                                                                 
 dropout_4 (Dropout)         (None, 60, 100)           0         
                                                                 
 lstm_5 (LSTM)               (None, 60, 100)           80400     
                                                                 
 dropout_5 (Dropout)         (None, 60, 100)           0         
                                                                 
 lstm_6 (LSTM)               (None, 60, 100)           80400     
                                                                 
 dropout_6 (Dropout)         (None, 60, 100)           0         
                                                                 
 lstm_7 (LSTM)               (None, 100)              

### Training/Fitting Model

In [26]:
r = model.fit(X_train, y_train, epochs=200, batch_size=32)

Epoch 1/200
7/7 [==============================] - 6s 46ms/step - loss: 0.0608
Epoch 2/200
7/7 [==============================] - 0s 23ms/step - loss: 0.0210
Epoch 3/200
7/7 [==============================] - 0s 23ms/step - loss: 0.0152
Epoch 4/200
7/7 [==============================] - 0s 25ms/step - loss: 0.0112
Epoch 5/200
7/7 [==============================] - 0s 24ms/step - loss: 0.0098
Epoch 6/200
7/7 [==============================] - 0s 24ms/step - loss: 0.0107
Epoch 7/200
7/7 [==============================] - 0s 23ms/step - loss: 0.0086
Epoch 8/200
7/7 [==============================] - 0s 24ms/step - loss: 0.0078
Epoch 9/200
7/7 [==============================] - 0s 24ms/step - loss: 0.0072
Epoch 10/200
7/7 [==============================] - 0s 24ms/step - loss: 0.0076
Epoch 11/200
7/7 [==============================] - 0s 23ms/step - loss: 0.0074
Epoch 12/200
7/7 [==============================] - 0s 23ms/step - loss: 0.0082
Epoch 13/200
7/7 [==============================]