# Recurrent Neural Network

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Data Preprocessing

In [2]:
dataset_train =  pd.read_csv("dataset_dl/ETH-USD.csv")
display(dataset_train)

Date         Open         High          Low        Close  \
0     2020-01-25   163.067291   163.227234   158.632477   161.283936   
1     2020-01-26   161.176819   168.220322   160.281128   168.077103   
2     2020-01-27   168.008850   172.922913   166.901093   170.930893   
3     2020-01-28   170.884857   176.370316   170.738068   176.370316   
4     2020-01-29   176.347885   178.842972   175.050339   175.050339   
...          ...          ...          ...          ...          ...   
1031  2022-11-21  1142.395752  1142.395752  1084.857300  1108.353027   
1032  2022-11-22  1107.895996  1136.442627  1081.138184  1135.173462   
1033  2022-11-23  1135.421509  1184.997314  1130.022827  1183.199585   
1034  2022-11-24  1183.345093  1211.627441  1180.379761  1203.983154   
1035  2022-11-25  1202.505493  1202.767212  1175.496216  1181.661621   

        Adj Close       Volume  
0      161.283936   8256956802  
1      168.077103   9261861590  
2      170.930893  11004476145  
3      176.370316  11772875064  
4      175.050339  10725267311  
...           ...          ...  
1031  1108.353027  14080099208  
1032  1135.173462  12040670755  
1033  1183.199585  11242676044  
1034  1203.983154   9706372376  
1035  1181.661621   8519430144  

[1036 rows x 7 columns]

In [3]:
# Opening price of ETH (in USD)
training_set = dataset_train.iloc[:,1:2].values

In [4]:
print(training_set)

[[ 163.067291]
 [ 161.176819]
 [ 168.00885 ]
 ...
 [1135.421509]
 [1183.345093]
 [1202.505493]]


In [7]:
# Feature Scalling by doing Normalization
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
training_set_scaled = sc.fit_transform(training_set)

In [16]:
print(training_set_scaled)
print(f"\nNo of Elemets: {len(training_set_scaled)}")

[[0.01120516]
 [0.01080291]
 [0.01225663]
 ...
 [0.21810381]
 [0.22830104]
 [0.23237802]]

No of Elemets: 1036


In [14]:
print("Statistical Summary of Feature Scaled Data:")
pd.DataFrame(training_set_scaled).describe()

Statistical Summary of Feature Scaled Data:


0
count  1036.000000
mean      0.346881
std       0.273399
min       0.000000
25%       0.060533
50%       0.319755
75%       0.566349
max       1.000000

In [21]:
# Creating a Data Structure with 60 timestamps (2 months) and 1 output

X_train = []
y_train = []
for i in range(60, len(training_set_scaled)):
    X_train.append(training_set_scaled[i-60:i,0])
    y_train.append(training_set_scaled[i,0])
    
X_train, y_train = np.array(X_train), np.array(y_train)

In [32]:
X_train[0]

array([0.01120516, 0.01080291, 0.01225663, 0.01286859, 0.01403102,
       0.01372671, 0.01581605, 0.01483233, 0.01555977, 0.01663962,
       0.01690651, 0.0167868 , 0.01994247, 0.02168434, 0.02385366,
       0.02395393, 0.02513846, 0.02403962, 0.02670221, 0.03290574,
       0.03353782, 0.0370568 , 0.03287411, 0.03180733, 0.03321557,
       0.03651952, 0.03179228, 0.03138188, 0.03301189, 0.03231542,
       0.0347468 , 0.03295482, 0.02922196, 0.02452947, 0.0248062 ,
       0.0247734 , 0.02326675, 0.02304523, 0.02555867, 0.02429079,
       0.02430708, 0.02527024, 0.02837296, 0.02710276, 0.0193443 ,
       0.01967314, 0.01922717, 0.01794429, 0.00048582, 0.00493135,
       0.00273196, 0.00310433, 0.        , 0.00073428, 0.00094327,
       0.00558391, 0.00482906, 0.00477573, 0.00275747, 0.00527428])

In [29]:
X_train.shape

(976, 60)

In [33]:
# Reshaping Data
X_train = np.reshape(X_train, newshape=(*X_train.shape,1))

In [34]:
X_train.shape

(976, 60, 1)

## Building RNN